### ISSUE TITLE
eval-buffer: Cannot open load file: not a directory, isend

### ISSUE THREAD

**Issue by ucsky** [ffevotte/isend-mode.el#12]
I'm doing:

    (add-to-list 'load-path "~/.emacs.d/isend-mode.el")                                                  |                                                                                                      
    (require 'isend) 

And I'm getting:

    eval-buffer: Cannot open load file: not a directory, isend

**Comment by ffevotte** [comment]
Sorry I missed you issue. Have you finally managed to successfully load `isend`?
