### ISSUE TITLE
Not working with the latest IPython console (moved away from pyreadline)

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [ffevotte/isend-mode.el#6]
Hi, I have been using `isend-mode`with `ansi-term` terminals in Emacs very happily for several years now and after upgrading IPython to [the latest version 5.0](http://blog.jupyter.org/2016/07/08/ipython-5-0-released/) it stopped working. It looks like they moved away from `pyreadline` to something called `prompt_toollkit`. 

Any thoughts on what could be going on ?

**Comment by amelio-vazquez-reina** [comment]
It's actually odd. It's not that I get any errors or anything. It's just that it sometimes (most of the times) it doesn't send anything, but sometimes it does..

**Comment by amelio-vazquez-reina** [comment]
In case it's helpful, here is the package that IPython relies on for its terminal: [Python Prompt Toolkit](https://github.com/jonathanslenders/python-prompt-toolkit). It actually seems to include some code to manage Emacs terms properly.

**Comment by amelio-vazquez-reina** [comment]
Also, to clarify, why i say it doesn't work, I specifically mean that, If I do `C-RET` on a given line, it most of the times just duplicates the current line without sending code (or `%paste` in my case) to it. E.g. of trying several times:
<img width="517" alt="screen shot 2016-07-17 at 12 50 42 am" src="https://cloud.githubusercontent.com/assets/1993919/16898831/b4664856-4bb8-11e6-9071-7ab341db3661.png">


<img width="517" alt="screen shot 2016-07-17 at 12 50 42 am" src="https://cloud.githubusercontent.com/assets/1993919/16898826/9621375c-4bb8-11e6-8c54-ec4f55965eb2.png">

**Comment by amelio-vazquez-reina** [comment]
Thanks @ffevotte. No problem at all! (responding here since I think this thread has a better description of the actual problem)

It all happens very quickly, but:

1. I see `"%paste"` (or `%cpaste`, whichever I am using) inserted in the terminal. I see it at the **bottom** of the buffer for a fraction of a second. 
2. Python reacts to it (as if only a `RET` had been inserted. I know this since it just creates a new line with the same prompt index, as in the screenshot above, and that's exactly what IPython does when you just manually enter `RET`)
3. I don't see any Python code expanded from the clipboard. This makes sense, since as per point 2. IPython is only interpreting a `RET`, i.e. it does not see the `%paste` so it can't expand it.

Does that make sense?

On a related note, in case you don't know this already, one super fast way of testing any Python package is to use [anaconda](https://www.continuum.io/downloads) MIT license to install binaries directly. You can have virtual envs. choose which version of what package to install etc.

**Comment by albertstartup** [comment]
@amelio-vazquez-reina I encountered the same problem as you.
The solution is to make the ipython repl reach past the bottom of the buffer.
The way i solved this is by commenting line 272:
(goto-char (point-max))

**Comment by albertstartup** [comment]
I would like to send a pull request, but I dont know if there are cases where going to "point-max" is nessesary.
If not, then the solution would be just to remove that line.

**Comment by albertstartup** [comment]
Instead of (point-max) it should be (process-mark (get-buffer-process (current-buffer)))

**Comment by ffevotte** [comment]
@albertstartup Thanks for your feedback. Have you also read #8 (not sure exactly why, but this discussion has been split into two parts...)

I agree that your fix should be the correct thing to do. But from the end of the discussion in #8, it looked like it wasn't necessary for recent Emacs versions...
